name: Waka Readme

on:
  schedule:
    # [0] minute 44 to avoid amount of traffic to wakatime;
    # [1] hour 是 UTC+0 时区，UTC+0 2/18 = UTC+8 10/2;
    - cron: '44 2,18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_PROJECTS: "False"
          SHOW_LOC_CHART: "False"
