name: Waka Readme

on:
  schedule:
    # [0] minitu 44 / hour 2 for avoiding amount of traffic to wakatime;
    # [1] GTM 18 == GTM+8 02 for another try at early morning;
    - cron: '44 2,18 * * *'   
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_PROJECTS: "False"
          SHOW_LOC_CHART: "False"
